name = "evm-voting"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Development environment (local testing)
[env.development]
vars = { SUPABASE_URL = "https://lijygukwbzxrkcpjxitp.supabase.co" }

# Production environment (Cloudflare Workers)
[env.production]
vars = { SUPABASE_URL = "https://lijygukwbzxrkcpjxitp.supabase.co" }
routes = [
  { pattern = "evm.shrey-cse-lnct.workers.dev/*", zone_name = "workers.dev" }
]


